//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginForma
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stan
    {
        public int ID { get; set; }
        public string Oznaka { get; set; }
        public int KatID { get; set; }
        public Nullable<int> StanarID { get; set; }
        public string StanIznajmljen { get; set; }
        public Nullable<System.DateTime> IznajmljenDoDatuma { get; set; }
        public string Napomena { get; set; }
        public Nullable<double> Dugovanje { get; set; }
    
        public virtual Kat Kat { get; set; }
        public virtual Stanar Stanar { get; set; }
    }
}
