//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginForma
{
    using System;
    using System.Collections.Generic;
    
    public partial class UgovorenPosao
    {
        public int ZgradaID { get; set; }
        public int TvrtkaID { get; set; }
        public int MoguciPosloviID { get; set; }
        public Nullable<double> Cijena { get; set; }
        public Nullable<System.DateTime> PocetakRada { get; set; }
        public Nullable<System.DateTime> KrajRada { get; set; }
    
        public virtual MogucPosao MogucPosao { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual Zgrada Zgrada { get; set; }
    }
}
