//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginForma
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ulaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ulaz()
        {
            this.Kats = new HashSet<Kat>();
        }
    
        public int ID { get; set; }
        public string Oznaka { get; set; }
        public string Adresa { get; set; }
        public int ZgradaID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kat> Kats { get; set; }
        public virtual Zgrada Zgrada { get; set; }
    }
}
