//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginForma
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uplatnica
    {
        public int ID { get; set; }
        public double Iznos { get; set; }
        public string OpisPlacanja { get; set; }
        public int StanarID { get; set; }
    
        public virtual Stanar Stanar { get; set; }
    }
}
